//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace magaFine.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class articles
    {
        public int Id { get; set; }
        public string AuthorId { get; set; }
        public string title { get; set; }
        public string cover { get; set; }
        [AllowHtml]
        public string content { get; set; }
        public string type { get; set; }
        public string category { get; set; }
        public string hearts { get; set; }
        public string hashtags { get; set; }
        public string popularity { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
        public Nullable<int> disploy { get; set; }
        public string parentId { get; set; }
        public string readAccess { get; set; }
    }
}
