//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace magaFine.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class magaFineEntities : DbContext
    {
        public magaFineEntities()
            : base("name=MySqlConnectionString")
        {
        }
    
        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    modelBuilder.Properties<decimal>().Configure(config => config.HasPrecision(18, 4));
        //    //throw new UnintentionalCodeFirstException();
        //}
    
        public virtual DbSet<articles> articles { get; set; }

        public virtual DbSet<users> users { get; set; }

        //internal void SaveChange()
        //{
        //    //throw new NotImplementedException();
        //    base.SaveChanges();
        //}
    }
}
